### ISSUE TITLE
How can use default arguments

### ISSUE THREAD

**Issue by jespanag** [MatthiWare/CommandLineParser.Core#137]
For example; 

If i want call a command without options:

`server "localhost" `

i need the first argument "localhost", without any option like --port.

Thanks !

**Comment by Matthiee** [comment]
Hi @jespanag 

We support option ordering.

If you are configuring the options using attributes you can just add 
```csharp
class MyModel
{
     [OptionOrder(0)]
     public string Hostname { get; set; }
}
```

Or if you are using the fluent API:

```csharp
parser
    .Configure(_ => _.Hostname)
    .Order(0);
```

**Comment by jespanag** [comment]
Thanks you!

Sorry for not having seen it before, greetings.
