### ISSUE TITLE
Allow RegisterCommand to receive Type arguments

### ISSUE THREAD

**Issue by thiagomajesk** [MatthiWare/CommandLineParser.Core#29]
Hi, the current interface is rather limiting for dealing with generic command loading. 
I would expect another overload like this: `RegisterCommand(typeof(Command), typeof(Options));`

**Comment by Matthiee** [comment]
Hi @thiagomajesk 

Indeed we should provide type based loading instead of only generic loading.

**Comment by Matthiee** [comment]
Hi @thiagomajesk 

Version 0.2.4 contains a fix for this issue.

https://www.nuget.org/packages/MatthiWare.CommandLineParser/0.2.4
