### ISSUE TITLE
Wiki: Configuration: Error in demo code

### ISSUE THREAD

**Issue by Storm-BE** [MatthiWare/CommandLineParser.Core#55]
Hi Matthi!

The [Configuration](https://github.com/MatthiWare/CommandLineParser.Core/wiki/Configuration) page on the project wiki contains following code:

```
var parseResult = parser.Parse(args);

if (result.HasErrors)
{
	Console.Error.WriteLine(result.Error);
	Console.ReadKey();

	return -1;
}
```

I suppose `result` should be `parseResult` there.
The issue is present in the demo code for Fluent API and Attributes config.

**Comment by Matthiee** [comment]
Oops, my bad! 

I updated the wiki.
